tappxi_web:
    resource: "@TappxiWebBundle/Controller/"
    type:     annotation
    prefix:   /

tappxi_api:
    resource: "@TappxiApiBundle/Controller/"
    type:     annotation
    prefix:   /api

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_welcome:
    pattern:  /
    defaults: { _controller: TappxiWebBundle:Default:index }
